// login reducer
export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
export const SET_LOGIN_SIGNUP_TOGGLE = 'SET_LOGIN_SIGNUP_TOGGLE';

// game reducer
export const ADD_PROMPT = 'ADD_PROMPT';
export const GET_USER_INPUT = 'GET_USER_INPUT';
export const SEND_AND_UPDATE_INPUT_TO_SERVER = 'SEND_AND_UPDATE_INPUT_TO_SERVER';
export const SEND_AND_UPDATE_VALID_WORDS = 'SEND_AND_UPDATE_VALID_WORDS';
export const SEND_AND_UPDATE_VALID_INPUT = 'SEND_AND_UPDATE_VALID_INPUT';
export const SEND_AND_UPDATE_INVALID_INPUT = 'SEND_AND_UPDATE_INVALID_INPUT';
export const SEND_AND_UPDATE_CURR_CHAR = 'SEND_AND_UPDATE_CURR_CHAR';
export const SEND_AND_UPDATE_NEXT_CHAR = 'SEND_AND_UPDATE_NEXT_CHAR';
export const SEND_AND_UPDATE_REMAINING_WORDS = 'SEND_AND_UPDATE_REMAINING_WORDS';